[package]
edition = "2021"
name = "spatial_derive"
version = "0.1.0"

[lib]
proc-macro = true

[dependencies]
petgraph = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true, features = ["extra-traits"] }
