[camera.top.calibration]
# The extrinsic rotation for the camera in degrees, xyz euler angles.
extrinsic_rotation = [-1.80, -5.12, 2.67]
# The focal length for the camera in pixels.
focal_lengths = [608, 609]
# The optical center of the camera sensor in pixels.
cc_optical_center = [320, 240]

[camera.bottom.calibration]
# The focal length for the camera in pixels.
focal_lengths = [289, 292]
# The optical center of the camera sensor in pixels.
cc_optical_center = [157, 120]
