[workspace]
members = ["crates/*", "tools/*", "yggdrasil"]
resolver = "2"

[workspace.package]
authors = ["Dutch Nao Team"]
categories = []
edition = "2021"
rust-version = "1.81.0"
version = "0.1.0"

[workspace.lints.rust]
# TODO: re-enable this once we have docs for everything
# missing_docs = "warn"
# TODO: replace this lint with cargo-machete, since it's broken
# https://github.com/rust-lang/rust/issues/57274
# unused_crate_dependencies = "warn"

[workspace.lints.clippy]
# enable clippy lints with priority -1
# so that we can override certain ones with "allow"
all = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }

inline_always = "allow"
module_name_repetitions = "allow"

[workspace.dependencies]
# root crates
yggdrasil = { path = "yggdrasil" }

# yggdrasil libraries
tasks = { path = "crates/tasks" }
ml = { path = "crates/ml" }
bifrost = { path = "crates/bifrost" }
odal = { path = "crates/odal" }
tyr = { path = "crates/tyr" }
heimdall = { path = "crates/heimdall" }
nilfheim = { path = "crates/nilfheim" }

# tools
sindri = { path = "tools/sindri" }
simulation = { path = "tools/simulation" }

# external crates
async-std = "1.13.0"
async-trait = "0.1.82"
byteorder = "1.4.3"
bevy = { version = "0.14.2", default-features = false }
cargo_toml = "0.19.2"
clap = "4.5.18"
cpal = { version = "0.15.3" }
colored = "2.0.4"
derive_more = "0.99.18"
dialoguer = "0.11.0"
dot-structures = "0.1.1"
dyn-clone = "1.0.17"
enum_dispatch = "0.3.13"
fast_image_resize = "3.0.4"
fast-math = "0.1.1"
futures = "0.3.30"
geo = "0.28.0"
glob = "0.3.1"
graphviz-rust = "0.9.0"
home = "0.5.9"
# We're stuck on this version until rerun updates
# https://github.com/rerun-io/rerun/pull/5280
image = "0.25.2"
itertools = "0.13.0"
indicatif = "0.17.8"
kira = "0.8.7"
linreg = "0.2.0"
linuxvideo = { git = "ssh://git@github.com/IntelligentRoboticsLab/linuxvideo.git", rev = "a66c7c23dbdafcd9b129744d7716820a979af48d" }
local-ip-address = "0.6.3"
miette = "5.10.0"
nalgebra = { version = "0.32.6" }
ndarray = "0.15.6"
nidhogg = { git = "ssh://git@github.com/IntelligentRoboticsLab/nidhogg.git", rev = "d654b62827e16314181fd9936c6e1828333aee93" }
num = "0.4.3"
openvino = { git = "https://github.com/YukumoHunter/openvino-rs.git", branch = "evil-hack", features = [
  "runtime-linking",
] }
ordered-float = "4.2.1"
lstsq = "0.5.0"
pathfinding = "4.11.0"
petgraph = "0.6.5"
proc-macro2 = "1.0.86"
quote = "1.0.37"
rand = "0.8.5"
rayon = "1.10.0"
regex = "1.10.5"
rerun = { version = "0.18.2", features = ["image"] }
rustfft = "6.2.0"
rustc_version = "0.4.1"
serde = "1.0.210"
serde_json = "1.0.128"
serde_with = "3.9.0"
ssh2 = "0.9.4"
syn = "2.0.77"
thiserror = "1.0.64"
tokio = "1.40.0"
tokio-test = "0.4.2"
tokio-tungstenite = "0.21.0"
toml = "0.8.16"
tracing = "0.1.37"
tracing-subscriber = "0.3"
tracing-appender = "0.2"
tracing-tracy = "0.11.3"
turbojpeg = "1.1.0"
walkdir = "2.5.0"
apodize = "1.0.0"
