[workspace]
members = ["yggdrasil", "crates/tyr"]

[workspace.dependencies]
color-eyre = "0.6.2"
dyn-clone = "1.0.11"
petgraph = "0.6.3"
proc-macro2 = "1.0.63"
quote = "1.0.28"
syn = "2.0.22"
nidhogg = { git = "ssh://git@github.com/IntelligentRoboticsLab/nidhogg.git", features = [
    "lola",
    "coppelia",
] }
rustc_version = "0.4.0"