[workspace]
members = ["yggdrasil", "crates/tyr"]

[workspace.dependencies]
miette = { version = "5.10.0" }
tracing = "0.1.37"
tracing-subscriber = "0.3"
dyn-clone = "1.0.11"
petgraph = "0.6.3"
proc-macro2 = "1.0.63"
quote = "1.0.28"
syn = "2.0.22"
nidhogg = { git = "ssh://git@github.com/IntelligentRoboticsLab/nidhogg.git", features = [
    "lola",
] }
derive_more = "0.99.17"
rustc_version = "0.4.0"
