[workspace]
members = ["yggdrasil", "crates/tyr", "crates/sindri"]

[workspace.dependencies]
clap = "4.4.3"
derive_more = "0.99.17"
dyn-clone = "1.0.11"
futures-lite = "1.13.0"
kira = "0.8.4"
miette = { version = "5.10.0" }
nidhogg = { git = "ssh://git@github.com/IntelligentRoboticsLab/nidhogg.git" }
petgraph = "0.6.3"
proc-macro2 = "1.0.63"
quote = "1.0.28"
rayon = "1.7.0"
rustc_version = "0.4.0"
syn = "2.0.22"
thiserror = "1.0.48"
tokio = { version = "1.31.0" }
tracing = "0.1.37"
tracing-subscriber = "0.3"
