[workspace]
members = ["crates/*", "yggdrasil"]
resolver = "2"

[workspace.dependencies]
alsa = "0.9.0"
async-trait = "0.1.80"
byteorder = "1.4.3"
cargo_toml = "0.19.2"
clap = "4.5.3"
colored = "2.0.4"
derive_more = "0.99.17"
dialoguer = "0.11.0"
dyn-clone = "1.0.17"
enum_dispatch = "0.3.13"
fast_image_resize = "3.0.4"
fast-math = "0.1.1"
futures = "0.3.28"
geo = "0.28.0"
glob = "0.3.1"
home = "0.5.9"
# We're stuck on this version until rerun updates
# https://github.com/rerun-io/rerun/pull/5280
image = "0.24.0"
indicatif = "0.17.8"
kira = "0.8.7"
linreg = "0.2.0"
linuxvideo = { git = "ssh://git@github.com/IntelligentRoboticsLab/linuxvideo.git", rev = "a66c7c23dbdafcd9b129744d7716820a979af48d" }
local-ip-address = "0.6.1"
miette = "5.10.0"
nalgebra = "0.32.5"
ndarray = "0.15.6"
nidhogg = { git = "ssh://git@github.com/IntelligentRoboticsLab/nidhogg.git", rev = "b4a4ac455cb67986a5ea4ffaa88a91e2a8cd9feb" }
num = "0.4.3"
openvino = { git = "https://github.com/YukumoHunter/openvino-rs.git", branch = "evil-hack", features = [
  "runtime-linking",
] }
ordered-float = "4.2.0"
lstsq = "0.5.0"
pathfinding = "4.9.1"
petgraph = "0.6.5"
proc-macro2 = "1.0.84"
quote = "1.0.36"
rayon = "1.10.0"
regex = "1.10.4"
rerun = { version = "0.16.0" }
rustfft = "6.2.0"
rustc_version = "0.4.0"
serde = "1.0.203"
serde_json = "1.0.117"
serde_with = "3.8.1"
ssh2 = "0.9.4"
syn = "2.0.66"
thiserror = "1.0.61"
tokio = "1.37.0"
tokio-test = "0.4.2"
tokio-tungstenite = "0.21.0"
toml = "0.8.11"
tracing = "0.1.37"
tracing-subscriber = "0.3"
turbojpeg = "1.1.0"
walkdir = "2.5.0"
