[workspace]
resolver = "2"
members = ["crates/*", "yggdrasil"]

[workspace.dependencies]
async-trait = "0.1.77"
byteorder = "1.4.3"
cargo_toml = "0.17.0"
clap = "4.4.18"
colored = "2.0.4"
dyn-clone = "1.0.11"
enum_dispatch = "0.3.12"
futures = "0.3.28"
image = "0.24.8"
indicatif = "0.17.6"
kira = "0.8.6"
linuxvideo = { git = "ssh://git@github.com/IntelligentRoboticsLab/linuxvideo.git" }
miette = "5.10.0"
nidhogg = { git = "ssh://git@github.com/IntelligentRoboticsLab/nidhogg.git" }
num = "0.4.0"
petgraph = "0.6.3"
proc-macro2 = "1.0.78"
quote = "1.0.35"
rayon = "1.8.1"
regex = "1.10.3"
rustc_version = "0.4.0"
serde = "1.0.195"
serde_json = "1.0.111"
serde_with = "3.5.0"
ssh2 = "0.9.4"
syn = "2.0.22"
thiserror = "1.0.56"
tokio = "1.31.0"
tokio-test = "0.4.2"
tokio-tungstenite = "0.20.0"
toml = "0.8.8"
tracing = "0.1.37"
tracing-subscriber = "0.3"
walkdir = "2.4.0"
