[package]
name = "yggdrasil_rerun"
version = "0.13.0"

authors.workspace = true
categories.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
bifrost = { workspace = true }
build_utils = { workspace = true }
heimdall = { workspace = true }
sindri = { workspace = true, default-features = false, features = ["config"] }

clap = { workspace = true, features = ["derive"] }
miette = { workspace = true }
mimalloc = { workspace = true }
nalgebra = { workspace = true }
yggdrasil_rerun_comms = { path = "yggdrasil_rerun_comms" }
re_crash_handler = { workspace = true }
rerun = { workspace = true, features = [
  "ecolor",
  "clap",
  "server",
  "sdk",
  "native_viewer",
  "run",
] }
strum = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }
tokio = { workspace = true, features = [
  "macros",
  "rt",
  "rt-multi-thread",
  "signal",
  "sync",
  "time",
] }
tracing = { workspace = true }
