[package]
edition = "2021"
name = "tyr_internal"
version = "0.1.0"

[lib]
name = "tyr_internal"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dot-structures = { workspace = true }
dyn-clone = { workspace = true }
graphviz-rust = { workspace = true }
itertools = { workspace = true }
miette = { workspace = true }
petgraph = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tracing = { workspace = true }
