[package]
name = "tyr_internal"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dyn-clone = { workspace = true }
miette = { workspace = true }
petgraph = { workspace = true }

[dev-dependencies]
tyr = { path = "../" }
