[package]
name = "tyr_macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
tyr_internal = { path = "../tyr_internal" }

[build-dependencies]
rustc_version = { workspace = true }
