[package]
name = "heimdall"
version = "0.1.0"
edition = "2021"

[dependencies]
image = { workspace = true }
linuxvideo = { workspace = true }
miette = { workspace = true }
nalgebra = { workspace = true }
thiserror = { workspace = true }
turbojpeg = { workspace = true }
