[package]
name = "heimdall"
version = "0.1.0"
edition = "2021"

[dependencies]
criterion = { workspace = true }
image = { workspace = true }
rscam = { workspace = true }
thiserror = { workspace = true }

[[bench]]
name = "rgb_conversion_bench"
harness = false
