[package]
name = "bifrost"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bifrost_derive = { path = "bifrost_derive" }
byteorder = { workspace = true }
num = { workspace = true }
thiserror = { workspace = true }
