[camera.top.calibration]
# The extrinsic rotation for the camera in degrees, xyz euler angles.
extrinsic_rotation = [-0.94, -4.59, -2.40]
# The focal length for the camera in pixels.
focal_lengths = [562, 560]
# The optical center of the camera sensor in pixels.
cc_optical_center = [343, 213]

[camera.bottom.calibration]
# The extrinsic rotation for the camera in degrees, xyz euler angles.
extrinsic_rotation = [-0.95, -0.43, 4.02]
# The focal length for the camera in pixels.
focal_lengths = [295, 298]
# The optical center of the camera sensor in pixels.
cc_optical_center = [150, 117]
