[package]
name = "yggdrasil"
version = "0.1.0"
edition = "2021"
default-run = "yggdrasil"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
alsa = { workspace = true, optional = true }
bifrost = { path = "../crates/bifrost/" }
enum_dispatch = { workspace = true }
heimdall = { path = "../crates/heimdall" }
kira = { workspace = true, optional = true }
miette = { workspace = true, features = ["fancy"] }
nalgebra = { workspace = true }
nidhogg = { workspace = true, features = ["lola"] }
odal = { path = "../crates/odal" }
rerun = { workspace = true, optional=true }
serde = { workspace = true }
serde_with = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tyr = { path = "../crates/tyr", features = ["odal"] }


[features]
default = []
alsa = ["dep:alsa", "dep:kira"]
rerun = ["dep:rerun"]
