[package]
name = "yggdrasil"
version = "0.1.0"
edition = "2021"
default-run = "yggdrasil"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bifrost = { path = "../crates/bifrost/" }
enum_dispatch = { workspace = true }
heimdall = { path = "../crates/heimdall" }
kira = { workspace = true }
miette = { workspace = true, features = ["fancy"] }
nidhogg = { workspace = true, features = ["lola"] }
odal = { path = "../crates/odal" }
serde = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tyr = { path = "../crates/tyr" }
