[package]
name = "yggdrasil"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
alsa = { workspace = true }
derive_more = { workspace = true }
kira = { workspace = true }
miette = { workspace = true, features = ["fancy"] }
nidhogg = { workspace = true, features = ["lola"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tyr = { path = "../crates/tyr" }
