[package]
name = "yggdrasil"
version = "0.1.0"
edition = "2021"
default-run = "yggdrasil"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
alsa = { workspace = true, optional = true }
bifrost = { path = "../crates/bifrost/" }
derive_more = { workspace = true }
enum_dispatch = { workspace = true }
fast-math = { workspace = true }
heimdall = { path = "../crates/heimdall" }
kira = { workspace = true, optional = true }
linreg = { workspace = true }
miette = { workspace = true, features = ["fancy"] }
nalgebra = { workspace = true }
ndarray = { workspace = true }
nidhogg = { workspace = true }
odal = { path = "../crates/odal" }
openvino = { workspace = true }
rerun = { workspace = true, optional = true, features = [
  "image",
  "web_viewer",
] }
serde = { workspace = true }
serde_with = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tyr = { path = "../crates/tyr", features = ["odal"] }

[features]
default = []
alsa = ["dep:alsa", "dep:kira"]
rerun = ["dep:rerun"]
local = []
