[package]
name = "yggdrasil"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.32.1"
nidhogg = { git = "ssh://git@github.com/IntelligentRoboticsLab/nidhogg.git" }
tyr = { workspace = true }
tokio = { workspace = true }
color-eyre = "0.6.2"
tracing-subscriber = "0.3.16"
tracing = "0.1.37"
