[package]
name = "yggdrasil"
version = "0.1.0"
edition = "2021"
default-run = "yggdrasil"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bifrost = { path = "../crates/bifrost/" }
heimdall = { path = "../crates/heimdall" }
kira = { workspace = true, optional = true }
futures = { workspace = true, optional = true }
miette = { workspace = true, features = ["fancy"] }
nidhogg = { workspace = true, default-features = false  }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tyr = { path = "../crates/tyr", optional = true }
tokio = { workspace = true, features = ["full"], optional = true }
tokio-tungstenite = { workspace = true, optional = true }

[features]
default = ["lola", "nidhogg/serde"]
lola = ["nidhogg/lola", "dep:tyr", "dep:tokio", "dep:tokio-tungstenite", "dep:kira", "dep:futures"]
