[package]
name = "yggdrasil"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bifrost = { workspace = true }
derive_more = { workspace = true }
futures = { workspace = true }
miette = { workspace = true, features = ["fancy"] }
nidhogg = { workspace = true, features = ["lola"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tyr = { path = "../crates/tyr" }
tokio = { workspace = true, features = ["full"] }
tokio-tungstenite = { workspace = true }
