[camera.top.calibration]
# The extrinsic rotation for the camera in degrees, xyz euler angles.
extrinsic_rotation = [2.05, -7.05, 4.26]
# The focal length for the camera in pixels.
focal_lengths = [597, 595]
# The optical center of the camera sensor in pixels.
cc_optical_center = [297, 228]

[camera.bottom.calibration]
# The focal length for the camera in pixels.
focal_lengths = [289, 292]
# The optical center of the camera sensor in pixels.
cc_optical_center = [159, 120]
