[package]
name = "sindri"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cargo_toml = { workspace = true }
tokio = { workspace = true }
clap = { workspace = true, features = ["derive"] }
miette = { workspace = true, features = ["fancy"] }
thiserror = { workspace = true }
colored = { workspace = true }
toml = { workspace = true }
serde = { workspace = true }
serde_with = { workspace = true }
indicatif = { workspace = true }
serde_json = { workspace = true }
regex = { workspace = true }
console = { workspace = true }