[observe]
# Controls how fast the robot moves its head back and forth while looking around
head_rotation_speed = 3.0
# Controls how far to the left and right the robot looks while looking around, in radians.
# If this value is one, the robot will look a maximum of one radian to the left and one
# radian to the right, etc.
head_yaw_max = 1.0
# Controls how far to the bottom the robot looks while looking around, in radians
head_pitch_max = 0.25

[rl_striker_search]
# The output of the policy is element wise multiplied with this value to determine the
# step that is requested to the walking engine.
policy_output_scaling = { forward = 0.05, left = 0.07, turn = 0.2 }
# Controls how fast the robot moves its head back and forth while looking around
head_rotation_speed = 3.0
# Controls how far to the left and right the robot looks while looking around, in radians.
# If this value is one, the robot will look a maximum of one radian to the left and one
# radian to the right, etc.
head_yaw_max = 1.0
# Controls how far to the bottom the robot looks while looking around, in radians
head_pitch_max = 0.25
