[field]
# This config contains the layout of the field as provided in the SPL rule book.
# A schematic overview is given below:
#
# .---------------------------------------------------------------------------.
# |                                                                           |
# |                                                                           |
# |        <----------------------------A--------------------------->         |
# |      .------------------------------------------------------------.       |
# |    ^ |                              |                             |       |
# |    | | <--G-->                      |                             |       |
# |    | |----------.                   |                  .----------|       |
# |    | |          | ^                 |                  |          |       |
# |    | |<E>       | |                 |                  |          |       |
# |    | |---.      | |                 |                  |      .---|       |
# |    | |   | ^    | |               -----                |      |   |       |
# |    | |   | |    | |              /  |  \               |      |   |       |
# |    B |   | F 0  | H             |<--J-->|              |  0<--I-->|       |
# |    | |   | |    | |              \  |  /               |      |   |       |
# |    | |   | v    | |               -----                |      |   |       |
# |    | |---.      | |                 |                  |      .---|       |
# |    | |          | |                 |                  |          |       |
# |    | |          | v                 |                  |          |       |
# |    | |----------.                   |                  .----------|       |
# |    | |                              |                             |       |
# |    v |                              |                             |<--K-->|
# |      .------------------------------------------------------------.       |
# |                                                                 ^         |
# |                                                                 K         |
# |                                                                 v         |
# .---------------------------------------------------------------------------.
#
# Here it is assumed the centre point as coordinates (0, 0).
# The x axis points towards the opponents' goal and runs parallel with A.
# The y axis points towards the top and runs parallel with B.

# Field length in millimeters (A).
length = 9.0

# Field width in millimeters (B).
width = 6.0

# Width of lines on the field (|).
line_width = 0.05

# Size of the penalty mark (0).
penalty_mark_size = 0.1

# Length of the goal area (E).
goal_area_length = 0.6

# Width of the goal area (F).
goal_area_width = 2.2

# Length of the penalty area (G).
penalty_area_length = 1.65

# Width of the penalty area (H).
penalty_area_width = 4

# Distance to the penalty mark from the side of the field (I).
penalty_mark_distance = 1.3

# Diameter of the centre circle (J).
centre_circle_diameter = 1.500

# Width of the border strip (K).
border_strip_width = 0.7
