robot_radius = 0.25
start_tolerance = 0.2
target_tolerance = 0.2
perpendicular_tolerance = 0.05
min_angular_tolerance = 0.05
max_angular_tolerance = 1.0
ease_in = 0.333
ease_out = 0.333
walk_speed = 0.045
turn_speed = 0.8
walking_turn_speed = 0.8
perpendicular_speed = 0.045
angular_speed = 0.1
