# Minimum luminance delta for there to be considered an edge between pixels.
min_edge_luminance_difference = 10.0

# Field color
max_field_hue = 80.0
max_field_luminance = 200.0
min_field_hue = 0.0
min_field_saturation = 45.0

# White color
max_white_saturation = 100.0
min_white_luminance = 90.0

# Black color
max_black_luminance = 60.0
max_black_saturation = 160.0

# Green chromaticity threshold
blue_chromaticity_threshold = 0.3    # not fine tuned
green_chromaticity_threshold = 0.430 # tuned
red_chromaticity_threshold = 0.3     # not fine tuned
