[target.aarch64-apple-darwin]
# TODO: A mac user fixes this shit

# HOMEBREW="$(brew --prefix)"

# export PATH="$HOMEBREW/opt/llvm/bin:$PATH"
# export LDFLAGS="-L$HOMEBREW/opt/llvm/lib"
# export CPPFLAGS="-I$HOMEBREW/opt/llvm/include"

# export TARGET_CC=x86_64-unknown-linux-gnu-gcc
# export CXX=x86_64-unknown-linux-gnu-g++
# export CC_X86_64_UNKNOWN_LINUX_GNU=x86_64-unknown-linux-gnu-gcc
# export CXX_X86_64_UNKNOWN_LINUX_GNU=x86_64-unknown-linux-gnu-g++
# export AR_X86_64_UNKNOWN_LINUX_GNU=x86_64-unknown-linux-gnu-ar
# export CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_LINKER=x86_64-unknown-linux-gnu-gcc

# # set cross compilation flags for alsa.
# ALSA_PREFIX=$(brew --prefix x86_64-unknown-linux-gnu-alsa-lib)
# export PKG_CONFIG_PATH="$ALSA_PREFIX/lib/x86_64-unknown-linux-gnu/pkgconfig"
# export PKG_CONFIG_LIB_DIR="$ALSA_PREFIX/lib/"
# export PKG_CONFIG_ALLOW_CROSS=1
