[package]
name = "bifrost_internal"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4.0"
thiserror = "1.0.38"
tokio = { version = "1.24.1", features = ["full"] }
async-trait = "0.1.62"
net2 = "0.2.38"
tokio-test = "0.4.2"
byteorder = "1.4.3"
bifrost_derive = { path = "../bifrost_derive" }
