[[motions]]
abort_conditions = []
angle_threshold = 0.3
angles = { head = { pitch = 0.0, yaw = 0.0 } }
complete_conditions = [
  { field = "GiroX", smaller_than = -0.3, bigger_than = 0.3 },
  { field = "GiroY", smaller_than = 0.3 },
  { field = "GiroY", bigger_than = -0.3 },
]
interpolation_weight = 0.5
max_delay = 3.0
min_delay = 1.0
# start_conditions = ["e.g. arms not below body"]
start_conditions = []
stiffness = { head_pitch = 0.0, head_yaw = 0.0 }
