[[key_frames]]
abort_conditions = []
complete_conditions = []
duration = 3.0
max_delay = 0.0
min_delay = 0.0
start_conditions = []
stiffness = 0.800000011920929

[key_frames.angles.head]
pitch = 0.3839724361896515
yaw = 0.0

[key_frames.angles.arms.left_arm]
elbow_roll = -1.2578380107879639
elbow_yaw = 0.20244598388671875
hand = 0.0
shoulder_pitch = 1.918992042541504
shoulder_roll = 0.12421202659606934
wrist_yaw = -0.052197933197021484

[key_frames.angles.arms.right_arm]
elbow_roll = 1.376039981842041
elbow_yaw = -0.14883995056152344
hand = 0.0
shoulder_pitch = 1.9620280265808105
shoulder_roll = -0.26695799827575684
wrist_yaw = 0.056715965270996094

[key_frames.angles.legs.left_leg]
ankle_pitch = 0.0
ankle_roll = 0.0
hip_pitch = 0.0
hip_roll = 0.0
hip_yaw_pitch = -0.0
knee_pitch = 1.919862151145935

[key_frames.angles.legs.right_leg]
ankle_pitch = 0.0
ankle_roll = 0.0
hip_pitch = 0.0
hip_roll = 0.0
knee_pitch = 1.919862151145935

[[key_frames]]
abort_conditions = []
complete_conditions = []
duration = 3.0
max_delay = 0.0
min_delay = 0.0
start_conditions = []
stiffness = 0.800000011920929

[key_frames.angles.head]
pitch = 0.3839724361896515
yaw = 0.0

[key_frames.angles.arms.left_arm]
elbow_roll = -1.2578380107879639
elbow_yaw = 0.20244598388671875
hand = 0.0
shoulder_pitch = 1.918992042541504
shoulder_roll = 0.12421202659606934
wrist_yaw = -0.052197933197021484

[key_frames.angles.arms.right_arm]
elbow_roll = 1.376039981842041
elbow_yaw = -0.14883995056152344
hand = 0.0
shoulder_pitch = 1.9620280265808105
shoulder_roll = -0.26695799827575684
wrist_yaw = 0.056715965270996094

[key_frames.angles.legs.left_leg]
ankle_pitch = 0.0
ankle_roll = 0.0
hip_pitch = -0.20000000298023224
hip_roll = 0.0
hip_yaw_pitch = -0.0
knee_pitch = -0.0872664600610733

[key_frames.angles.legs.right_leg]
ankle_pitch = 0.0
ankle_roll = 0.0
hip_pitch = -0.20000000298023224
hip_roll = 0.0
knee_pitch = -0.0872664600610733

[[key_frames]]
abort_conditions = []
complete_conditions = []
duration = 3.0
max_delay = 0.0
min_delay = 0.0
start_conditions = []
stiffness = 0.800000011920929

[key_frames.angles.head]
pitch = 0.3839724361896515
yaw = 0.0

[key_frames.angles.arms.left_arm]
elbow_roll = -1.2578380107879639
elbow_yaw = 0.20244598388671875
hand = 0.0
shoulder_pitch = 1.918992042541504
shoulder_roll = 0.12421202659606934
wrist_yaw = -0.052197933197021484

[key_frames.angles.arms.right_arm]
elbow_roll = 1.376039981842041
elbow_yaw = -0.14883995056152344
hand = 0.0
shoulder_pitch = 1.9620280265808105
shoulder_roll = -0.26695799827575684
wrist_yaw = 0.056715965270996094

[key_frames.angles.legs.left_leg]
ankle_pitch = 1.0471975803375244
ankle_roll = 0.0872664600610733
hip_pitch = 0.27925267815589905
hip_roll = 0.0
hip_yaw_pitch = -0.0
knee_pitch = -0.0872664600610733

[key_frames.angles.legs.right_leg]
ankle_pitch = 1.0471975803375244
ankle_roll = -0.0872664600610733
hip_pitch = 0.27925267815589905
hip_roll = 0.0
knee_pitch = -0.0872664600610733

[[key_frames]]
abort_conditions = []
complete_conditions = []
duration = 4.0
max_delay = 0.0
min_delay = 0.0
start_conditions = []
stiffness = 0.800000011920929

[key_frames.angles.head]
pitch = 0.3839724361896515
yaw = 0.0

[key_frames.angles.arms.left_arm]
elbow_roll = -1.2578380107879639
elbow_yaw = 0.20244598388671875
hand = 0.0
shoulder_pitch = 1.918992042541504
shoulder_roll = 0.12421202659606934
wrist_yaw = -0.052197933197021484

[key_frames.angles.arms.right_arm]
elbow_roll = 1.376039981842041
elbow_yaw = -0.14883995056152344
hand = 0.0
shoulder_pitch = 1.9620280265808105
shoulder_roll = -0.26695799827575684
wrist_yaw = 0.056715965270996094

[key_frames.angles.legs.left_leg]
ankle_pitch = 0.0
ankle_roll = 0.0
hip_pitch = -1.3962633609771729
hip_roll = 0.0
hip_yaw_pitch = -0.0
knee_pitch = -0.0872664600610733

[key_frames.angles.legs.right_leg]
ankle_pitch = 0.0
ankle_roll = 0.0
hip_pitch = -1.3962633609771729
hip_roll = 0.0
knee_pitch = -0.0872664600610733

[[key_frames]]
abort_conditions = []
complete_conditions = []
duration = 3.0
max_delay = 0.0
min_delay = 0.0
start_conditions = []
stiffness = 0.800000011920929

[key_frames.angles.head]
pitch = 0.3839724361896515
yaw = 0.0

[key_frames.angles.arms.left_arm]
elbow_roll = 0.03490658476948738
elbow_yaw = -1.2217304706573486
hand = 0.0
shoulder_pitch = 2.094395160675049
shoulder_roll = 0.0872664600610733
wrist_yaw = -1.5707963705062866

[key_frames.angles.arms.right_arm]
elbow_roll = -0.03490658476948738
elbow_yaw = 1.2217304706573486
hand = 0.0
shoulder_pitch = 2.094395160675049
shoulder_roll = -0.0872664600610733
wrist_yaw = 1.5707963705062866

[key_frames.angles.legs.left_leg]
ankle_pitch = 0.1745329201221466
ankle_roll = -0.1745329201221466
hip_pitch = -0.8726646304130554
hip_roll = 0.2617993950843811
hip_yaw_pitch = 0.9599310755729675
knee_pitch = -0.0872664600610733

[key_frames.angles.legs.right_leg]
ankle_pitch = 0.1745329201221466
ankle_roll = 0.1745329201221466
hip_pitch = -0.8726646304130554
hip_roll = -0.2617993950843811
knee_pitch = -0.0872664600610733

[[key_frames]]
abort_conditions = []
complete_conditions = []
duration = 3.0
max_delay = 0.0
min_delay = 0.0
start_conditions = []
stiffness = 0.800000011920929

[key_frames.angles.head]
pitch = 0.3839724361896515
yaw = 0.0

[key_frames.angles.arms.left_arm]
elbow_roll = -0.33161255717277527
elbow_yaw = -1.483529806137085
hand = 0.0
shoulder_pitch = 2.094395160675049
shoulder_roll = -0.0872664600610733
wrist_yaw = -1.5707963705062866

[key_frames.angles.arms.right_arm]
elbow_roll = -0.3839724361896515
elbow_yaw = 1.5184364318847656
hand = 0.0
shoulder_pitch = 2.1118483543395996
shoulder_roll = -0.01745329238474369
wrist_yaw = 1.5707963705062866

[key_frames.angles.legs.left_leg]
ankle_pitch = 0.8552113175392151
ankle_roll = -0.12217304855585098
hip_pitch = -1.3962633609771729
hip_roll = 0.7330383062362671
hip_yaw_pitch = 1.1344640254974365
knee_pitch = 1.3351768255233765

[key_frames.angles.legs.right_leg]
ankle_pitch = 0.8203047513961792
ankle_roll = 0.01745329238474369
hip_pitch = -1.4660766124725342
hip_roll = -0.5672320127487183
knee_pitch = 1.4311699867248535

[[key_frames]]
abort_conditions = []
complete_conditions = []
duration = 4.0
max_delay = 0.0
min_delay = 0.0
start_conditions = []
stiffness = 0.800000011920929

[key_frames.angles.head]
pitch = 0.3839724361896515
yaw = 0.0

[key_frames.angles.arms.left_arm]
elbow_roll = -0.27925267815589905
elbow_yaw = -1.483529806137085
hand = 0.0
shoulder_pitch = 2.0245819091796875
shoulder_roll = -0.13962633907794952
wrist_yaw = -1.5707963705062866

[key_frames.angles.arms.right_arm]
elbow_roll = -0.13962633907794952
elbow_yaw = 1.7278759479522705
hand = 0.0
shoulder_pitch = 2.1118483543395996
shoulder_roll = -0.6981316804885864
wrist_yaw = 1.5707963705062866

[key_frames.angles.legs.left_leg]
ankle_pitch = -0.7155849933624268
ankle_roll = -0.33161255717277527
hip_pitch = -0.5235987901687622
hip_roll = 0.20943951606750488
hip_yaw_pitch = 1.1344640254974365
knee_pitch = 2.1118483543395996

[key_frames.angles.legs.right_leg]
ankle_pitch = 0.9250245094299316
ankle_roll = -0.01745329238474369
hip_pitch = -1.535889744758606
hip_roll = -0.3490658402442932
knee_pitch = 0.8377580642700195

[[key_frames]]
abort_conditions = []
complete_conditions = []
duration = 3.0
max_delay = 0.0
min_delay = 0.0
start_conditions = []
stiffness = 0.800000011920929

[key_frames.angles.head]
pitch = 0.3839724361896515
yaw = 0.0

[key_frames.angles.arms.left_arm]
elbow_roll = -0.27925267815589905
elbow_yaw = -1.483529806137085
hand = 0.0
shoulder_pitch = 2.0245819091796875
shoulder_roll = -0.13962633907794952
wrist_yaw = -1.5707963705062866

[key_frames.angles.arms.right_arm]
elbow_roll = -0.13962633907794952
elbow_yaw = 1.7278759479522705
hand = 0.0
shoulder_pitch = 2.1118483543395996
shoulder_roll = -0.6981316804885864
wrist_yaw = 1.5707963705062866

[key_frames.angles.legs.left_leg]
ankle_pitch = -0.7155849933624268
ankle_roll = -0.33161255717277527
hip_pitch = -0.5235987901687622
hip_roll = 0.20943951606750488
hip_yaw_pitch = 1.1344640254974365
knee_pitch = 2.1118483543395996

[key_frames.angles.legs.right_leg]
ankle_pitch = 0.9250245094299316
ankle_roll = -0.01745329238474369
hip_pitch = -1.535889744758606
hip_roll = -0.3490658402442932
knee_pitch = 0.8377580642700195

[[key_frames]]
abort_conditions = []
complete_conditions = []
duration = 4.0
max_delay = 0.0
min_delay = 0.0
start_conditions = []
stiffness = 0.800000011920929

[key_frames.angles.head]
pitch = 0.3839724361896515
yaw = 0.0

[key_frames.angles.arms.left_arm]
elbow_roll = -0.2617993950843811
elbow_yaw = -1.483529806137085
hand = 0.0
shoulder_pitch = 1.7453292608261108
shoulder_roll = 0.36651915311813354
wrist_yaw = -1.5707963705062866

[key_frames.angles.arms.right_arm]
elbow_roll = -0.15707963705062866
elbow_yaw = 1.7278759479522705
hand = 0.0
shoulder_pitch = 1.8675023317337036
shoulder_roll = -0.3490658402442932
wrist_yaw = 1.5707963705062866

[key_frames.angles.legs.left_leg]
ankle_pitch = -1.0122909545898438
ankle_roll = 0.1745329201221466
hip_pitch = -0.5585053563117981
hip_roll = 0.06981316953897476
hip_yaw_pitch = 1.1344640254974365
knee_pitch = 2.1118483543395996

[key_frames.angles.legs.right_leg]
ankle_pitch = 0.9250245094299316
ankle_roll = 0.06981316953897476
hip_pitch = -0.3141592741012573
hip_roll = -0.2617993950843811
knee_pitch = -0.0872664600610733

[[key_frames]]
abort_conditions = []
complete_conditions = []
duration = 4.0
max_delay = 0.0
min_delay = 0.0
start_conditions = []
stiffness = 0.800000011920929

[key_frames.angles.head]
pitch = 0.3839724361896515
yaw = 0.0

[key_frames.angles.arms.left_arm]
elbow_roll = -0.2617993950843811
elbow_yaw = -1.483529806137085
hand = 0.0
shoulder_pitch = 1.5707963705062866
shoulder_roll = 0.36651915311813354
wrist_yaw = -1.5707963705062866

[key_frames.angles.arms.right_arm]
elbow_roll = -0.15707963705062866
elbow_yaw = 1.7278759479522705
hand = 0.0
shoulder_pitch = 1.7278759479522705
shoulder_roll = 0.0
wrist_yaw = 1.5707963705062866

[key_frames.angles.legs.left_leg]
ankle_pitch = -0.9773843884468079
ankle_roll = 0.15707963705062866
hip_pitch = -0.9599310755729675
hip_roll = 0.20943951606750488
hip_yaw_pitch = 0.7592182159423828
knee_pitch = 2.1118483543395996

[key_frames.angles.legs.right_leg]
ankle_pitch = -0.27925267815589905
ankle_roll = 0.2617993950843811
hip_pitch = -0.767944872379303
hip_roll = 0.235619455575943
knee_pitch = 1.6580628156661987

[[key_frames]]
abort_conditions = []
complete_conditions = []
duration = 3.0
max_delay = 0.0
min_delay = 0.0
start_conditions = []
stiffness = 0.800000011920929

[key_frames.angles.head]
pitch = 0.3839724361896515
yaw = 0.0

[key_frames.angles.arms.left_arm]
elbow_roll = -0.24434609711170197
elbow_yaw = -1.483529806137085
hand = 0.0
shoulder_pitch = 1.5184364318847656
shoulder_roll = 0.33161255717277527
wrist_yaw = -1.5707963705062866

[key_frames.angles.arms.right_arm]
elbow_roll = -0.13962633907794952
elbow_yaw = 1.7278759479522705
hand = 0.0
shoulder_pitch = 1.4137166738510132
shoulder_roll = -0.19198621809482574
wrist_yaw = 1.5707963705062866

[key_frames.angles.legs.left_leg]
ankle_pitch = -0.8552113175392151
ankle_roll = 0.13089969754219055
hip_pitch = -1.0471975803375244
hip_roll = -0.12217304855585098
hip_yaw_pitch = 0.5759586691856384
knee_pitch = 2.1118483543395996

[key_frames.angles.legs.right_leg]
ankle_pitch = -0.8901179432868958
ankle_roll = -0.15707963705062866
hip_pitch = -0.9948377013206482
hip_roll = 0.15707963705062866
knee_pitch = 2.1118483543395996

[[key_frames]]
abort_conditions = []
complete_conditions = []
duration = 6.0
max_delay = 0.0
min_delay = 0.0
start_conditions = []
stiffness = 0.800000011920929

[key_frames.angles.head]
pitch = 0.3839724361896515
yaw = 0.0

[key_frames.angles.arms.left_arm]
elbow_roll = -0.24434609711170197
elbow_yaw = -1.483529806137085
hand = 0.0
shoulder_pitch = 1.5184364318847656
shoulder_roll = 0.33161255717277527
wrist_yaw = -1.5707963705062866

[key_frames.angles.arms.right_arm]
elbow_roll = -0.13962633907794952
elbow_yaw = 1.7278759479522705
hand = 0.0
shoulder_pitch = 1.4137166738510132
shoulder_roll = -0.19198621809482574
wrist_yaw = 1.5707963705062866

[key_frames.angles.legs.left_leg]
ankle_pitch = -0.8552113175392151
ankle_roll = 0.13089969754219055
hip_pitch = -1.0471975803375244
hip_roll = -0.12217304855585098
hip_yaw_pitch = 0.44999998807907104
knee_pitch = 2.1118483543395996

[key_frames.angles.legs.right_leg]
ankle_pitch = -0.8901179432868958
ankle_roll = -0.15707963705062866
hip_pitch = -0.9948377013206482
hip_roll = 0.15707963705062866
knee_pitch = 2.1118483543395996

[[key_frames]]
abort_conditions = []
complete_conditions = []
duration = 5.0
max_delay = 0.0
min_delay = 0.0
start_conditions = []
stiffness = 0.800000011920929

[key_frames.angles.head]
pitch = 0.3490658402442932
yaw = 0.0

[key_frames.angles.arms.left_arm]
elbow_roll = -0.00800000037997961
elbow_yaw = -1.5700000524520874
hand = 0.0
shoulder_pitch = 1.5700000524520874
shoulder_roll = 0.20000000298023224
wrist_yaw = 0.0

[key_frames.angles.arms.right_arm]
elbow_roll = 0.00800000037997961
elbow_yaw = 1.5700000524520874
hand = 0.0
shoulder_pitch = 1.5700000524520874
shoulder_roll = -0.20000000298023224
wrist_yaw = 0.0

[key_frames.angles.legs.left_leg]
ankle_pitch = -0.6000000238418579
ankle_roll = 0.0
hip_pitch = -0.30000001192092896
hip_roll = 0.0
hip_yaw_pitch = -0.013799999840557575
knee_pitch = 0.9300000071525574

[key_frames.angles.legs.right_leg]
ankle_pitch = -0.6000000238418579
ankle_roll = 0.0
hip_pitch = -0.30000001192092896
hip_roll = 0.0
knee_pitch = 0.9300000071525574
