global_interpolation_type = "EaseInOut"
motion_order = [
    "flossdance/floss_start",
    "flossdance/floss_left_1",
    "flossdance/floss_left_2",
    "flossdance/floss_left_1",
    "flossdance/floss_right_1",
    "flossdance/floss_right_2",
    "flossdance/floss_right_1",
    "flossdance/floss_finish",
]