interpolation_type = "Linear"
motion_order = [
    "FlossDance/ReadyToFloss",
    "FlossDance/FlossLeft1",
    "FlossDance/FlossLeft2",
    "FlossDance/FlossLeft1",
    "FlossDance/FlossRight1",
    "FlossDance/FlossRight2",
    "FlossDance/FlossRight1",
    "FlossDance/FlossFinish",
]
