global_interpolation_type = "EaseInOut"
motion_order = [
    "floss_dance/floss_start",
    "floss_dance/floss_left_1",
    "floss_dance/floss_left_2",
    "floss_dance/floss_left_1",
    "floss_dance/floss_right_1",
    "floss_dance/floss_right_2",
    "floss_dance/floss_right_1",
    "floss_dance/floss_finish",
]