global_interpolation_type = "Linear"
exit_routine = "Standing"
motion_order = [
    "standup/on_stomach/lying_to_yoga",
    "standup/on_stomach/yoga_to_sitting",
    "standup/on_stomach/sitting_to_halfcrouch",
    "standup/halfcrouch_to_sit",
    "standup/extend_legs",
]
