interpolation_type = "Linear"
exit_message = Standing
motion_order = [
    "Standup/OnStomach/LyingToYoga",
    "Standup/OnStomach/YogaToSitting",
    "Standup/OnStomach/SittingToHalfCrouch",
    "Standup/HalfCrouchToSit",
    "Standup/ExtendLegs",
]