global_interpolation_type = "Linear"
exit_routine = "Standing"
motion_order = [
    "standup/on_back/ready_to_kick",
    "standup/on_back/kick_up",
    "standup/on_back/halfsit_to_halfcrouch",
    "standup/halfcrouch_to_sit",
    "standup/extend_legs",
]
