[camera.top.calibration]
# The extrinsic rotation for the camera in degrees, xyz euler angles.
extrinsic_rotation = [-0.92, -4.59, 5.38]
# The focal length for the camera in pixels.
focal_lengths = [603, 602]
# The optical center of the camera sensor in pixels.
cc_optical_center = [311, 244]

[camera.bottom.calibration]
# The focal length for the camera in pixels.
focal_lengths = [292, 295]
# The optical center of the camera sensor in pixels.
cc_optical_center = [164, 112]
