[package]
name = "tyr_tasks"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = { workspace = true }
miette = { workspace = true }
rayon = { workspace = true }
serde = { workspace = true, optional = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tyr_internal = { path = "../tyr_internal" }

[features]
serde = ["dep:serde"]
