[package]
edition = "2021"
name = "tyr_tasks"
version = "0.1.0"

[lib]
name = "tyr_tasks"

[dependencies]
futures = { workspace = true }
miette = { workspace = true }
odal = { path = "../../odal", optional = true }
rayon = { workspace = true }
serde = { workspace = true, optional = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tracing = { workspace = true }
tyr_internal = { path = "../tyr_internal" }

[features]
odal = ["dep:odal", "dep:serde"]
