[package]
name = "bifrost_derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.53"
quote = "1.0.23"
syn = { version = "2.0.6", features = ["full", "extra-traits"] }
