[camera.top.calibration]
# The extrinsic rotation for the camera in degrees, xyz euler angles.
extrinsic_rotation = [0.48, -5.46, -0.75]
# The focal length for the camera in pixels.
focal_lengths = [582, 583]
# The optical center of the camera sensor in pixels.
cc_optical_center = [327, 255]

[camera.bottom.calibration]
# The focal length for the camera in pixels.
focal_lengths = [295, 292]
# The optical center of the camera sensor in pixels.
cc_optical_center = [153, 117]
