[package]
name = "odal"
version = "0.1.0"
edition = "2021"

[dependencies]
miette = { workspace = true }
thiserror = { workspace = true }
toml = { workspace = true }
tracing = { workspace = true }
serde = { workspace = true }
