[package]
name = "tyr"
version = "0.1.0"
edition = "2021"

[dependencies]
tyr_internal = { path = "tyr_internal" }
tyr_macros = { path = "tyr_macros" }

[dev-dependencies]
tracing-subscriber = "0.3"
nidhogg = { workspace = true, features = ["lola", "coppelia"] }
color-eyre = { workspace = true }
