[package]
authors.workspace = true
categories.workspace = true
edition.workspace = true
name = "filter"
rust-version.workspace = true
version.workspace = true

[dependencies]
nalgebra = { workspace = true }
thiserror = { workspace = true }

[lints]
workspace = true

[dev-dependencies]
plotters = { workspace = true }
rand = { workspace = true }
