name: bondi wrapper
on:
  workflow_call:
    secrets:
      BONDI_DEPLOY_KEY:
        required: true
jobs:
  cicd:
    uses: IntelligentRoboticsLab/bondi/.github/workflows/rust.yml@main
    secrets:
      BONDI_DEPLOY_KEY: ${{ secrets.BONDI_DEPLOY_KEY }}
