name: Continuous Disappointment
on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]
    paths-ignore:
      - "deploy/**"

env:
  OPENVINO_SKIP_LINKING: 1
  CARGO_NET_GIT_FETCH_WITH_CLI: true
  CARGO_TERM_COLOR: always
  RUSTDOCFLAGS: -D warnings

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  test:
    name: cargo test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-github-pat/
        with:
          CI_TOKEN: ${{ secrets.CI_TOKEN }}
      - uses: ./.github/actions/install-ubuntu-deps/
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: 1.87
      - run: cargo test --all-features

  clippy:
    name: cargo clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-github-pat/
        with:
          CI_TOKEN: ${{ secrets.CI_TOKEN }}
      - uses: ./.github/actions/install-ubuntu-deps/
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: 1.87
          components: clippy
      - run: cargo clippy --all-targets --all-features -- -D warnings

  fmt:
    name: cargo fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-github-pat/
        with:
          CI_TOKEN: ${{ secrets.CI_TOKEN }}
      - uses: ./.github/actions/install-ubuntu-deps/
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: 1.87
          components: fmt
      - uses: uncenter/setup-taplo@v1
        with:
          version: "0.8.1"
      - run: cargo fmt --all -- --check
      - uses: crate-ci/typos@master
      - run: taplo fmt --check

  doc:
    name: cargo doc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-github-pat/
        with:
          CI_TOKEN: ${{ secrets.CI_TOKEN }}
      - uses: ./.github/actions/install-ubuntu-deps/
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: 1.87
          components: clippy
      - run: cargo doc --all-features --no-deps

  shear:
    name: cargo shear
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-github-pat/
        with:
          CI_TOKEN: ${{ secrets.CI_TOKEN }}
      - uses: cargo-bins/cargo-binstall@main
      - run: cargo binstall --no-confirm cargo-shear
      - run: cargo shear
