[package]
name = "simulation"

authors.workspace = true
categories.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
bifrost = { workspace = true }
yggdrasil = { workspace = true }

bevy = { workspace = true }
bevy_egui = { workspace = true }
nalgebra = { workspace = true }
filter = { version = "0.1.0", path = "../../crates/filter" }
ml = { workspace = true }
tasks = { workspace = true }

nidhogg = { workspace = true }
serde = { workspace = true }
