[package]
name = "simulation"

authors.workspace = true
categories.workspace = true
edition.workspace = true
rust-version.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
bifrost = { workspace = true }
yggdrasil = { workspace = true }

eframe = "0.28.1"
egui = "0.28.1"
egui_extras = { version = "0.28.1", features = ["default", "image"] }
env_logger = "0.11.5"
home = { workspace = true }
miette = { workspace = true }
nalgebra = { workspace = true }
nidhogg = { workspace = true }
rand = "0.8.5"
toml = { workspace = true }
